name: MoonCode Extension CI/CD Pipeline - Bump and publish extension version

on:
  push:
    branches: "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Publish
        #  build the dashboard first then the extension
        # for that we need to build the trpc and common packages
        # trpc needs to get its types from the api build
        run: |
          npm run build --workspace=@repo/common
          npm run build --workspace=api
          npm run build --workspace=@repo/trpc
          npm run build --workspace=dashboard
          npm run publish:patch --workspace=mooncode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          VITE_API_URL: ${{secrets.VITE_API_URL}}
          VITE_LOGIN_URL: ${{secrets.VITE_LOGIN_URL}}
          VITE_REGISTER_URL: ${{secrets.VITE_REGISTER_URL}}
          VITE_LOGOUT_URL: ${{secrets.VITE_LOGOUT_URL}}
          VITE_AUTH_GOOGLE_URL: ${{secrets.VITE_AUTH_GOOGLE_URL}}
